# https://pre-commit.com

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev:  v6.0.0
    hooks:
      - id:    check-yaml
        files: \.ya?ml$
  - repo: https://github.com/golangci/golangci-lint
    rev:  v2.11.4
    hooks:
      - id:    golangci-lint
        entry: golangci-lint run --verbose # or `go run github.com/golangci/golangci-lint/cmd/golangci-lint run`
  - repo: local
    hooks:
      - language:       system
        id:             go-test
        name:           go test
        entry:          go test -v -race ./...
        files:          \.go$|^go\.(?:mod|sum)$
        pass_filenames: false
        require_serial: true
      - language:       system
        id:             validate-actions-and-workflows
        name:           validate actions and workflows
        entry:          node validate.js
        files:          \.ya?ml$
        pass_filenames: false
      - language: system
        id:       eslint
        name:     eslint
        entry:    npx eslint --config demo/eslint.config.js --
        files:    \.m?js$
      - language: system
        id:       stylelint
        name:     stylelint
        entry:    npx stylelint --formatter verbose --
        files:    \.css$

