// Package main writes HTML files for each Go source file listed in the user-specified Go coverage profile file.
//
// This module also generates a directory tree HTML file rendered within an iframe of the index HTML file.
//
// The header portion of the index HTML file will also render two buttons if the browser's CORS policies allow it. These buttons are:
//
//   "expand" (or "collapse") - toggles opening (or closing) all subdirectories of the source tree
//   "lines"                  - toggles showing or hiding a column of line numbers along the left side of the source code
//   "theme"                  - toggles between "light" and "dark" themes
//
// Note that the "expand" / "collapse", "lines", and "theme" buttons will not be rendered when the index page is loaded via the file:// scheme.
package main

import (
	"bufio"
	"bytes"
	"cmp"
	"context"
	"embed"
	"flag"
	"fmt"
	"io"
	"io/fs"
	"maps"
	"net/url"
	"os"
	"os/exec"
	"os/signal"
	"path/filepath"
	"runtime"
	"slices"
	"strconv"
	"strings"
	"sync/atomic"
	"syscall"
	"testing"

	"golang.org/x/mod/modfile"
	"golang.org/x/term"
	"golang.org/x/tools/cover"
	"golang.org/x/tools/go/packages"
)

//go:embed html/* img/* css/* js/*
var embeddedFiles embed.FS

// coverage tracks per-file coverage.
type coverage struct {
	covered uint64
	total   uint64
}

// reportGenerator orchestrates the generation of the HTML report.
type reportGenerator struct {
	fsys             writeFS             // wrapper around the os functions used herein
	embeddedFiles    fs.FS               // templates and static files referenced by the generated HTML
	modFile          string              // path to go.mod
	modName          string              // module name
	repoURL          string              // repository URL written to the repo link in index.html template via .ModURL
	outRoot          rootHandle          // value of the -path flag
	profilePath      string              // value of the -coverprofile flag
	profiles         []*cover.Profile    // coverage profiles generated by `go tool cover`
	pkgDirCache      map[string]string   // pkgDirCache maps canonical Go packages to their respective paths on disk
	cov              map[string]coverage // per-file coverage stats
	totalCovered     atomic.Uint64        // module-wide total number of statements covered
	totalStatements  atomic.Uint64        // module-wide total number of statements
	staticFiles      []string            // static CSS, HTML, and image files required by the generated HTML
	styleCSSFilename string              // name of the CSS file included by index.html and generated source HTML files
	childJSFilename  string              // name of the JS file included by generated source HTML files that handles toggling the theme and line numbers
}

func main() {
	os.Exit(run())
}

func run() int {
	ctx, stop := signal.NotifyContext(context.Background(),
		os.Interrupt,    // ctrl+c
		syscall.SIGTERM, // standard kill signal
		syscall.SIGHUP,  // terminal closed, SSH disconnection, etc
	)
	defer stop()

	indexHTMLFile := "html/index.html" // embedded template (.ModName, .ModURL, .TreeHTML)

	goModFile, profilePath, outDir, noBrowser, err := flags(flag.CommandLine, filterArgs(os.Args[1:]))
	if err != nil { return fatal(1, "cannot parse flags: %v\n", err) }

	profiles, err := cover.ParseProfiles(profilePath) // TODO(jbunds): (maybe?) add an adapter to handle both legacy textfmt and binary coverage profiles
	if err != nil { return fatal(2, "cannot parse coverage profile file: %v\n", err) }

	fmt.Fprintf(os.Stderr, "processing %d source files...", len(profiles))
	if !isTerm(os.Stderr) { fmt.Println() } // nolint:forbidigo

	repGen, err := newReportGenerator(goModFile, profilePath, profiles, outDir)
	if err != nil { return fatal(3, "cannot instantiate report generator: %v\n", err) }
	defer repGen.outRoot.Close()

	if err := repGen.getModName(ctx, goModFile); err != nil { return fatal(4, "cannot determine module name: %v\n", err) }

	if err := repGen.getRemoteURL(new(realRunner), goModFile); err != nil { return fatal(6, "cannot determine remote URL: %v\n", err) }

	if err := repGen.primePkgDirCache(ctx, packages.Load); err != nil { return fatal(7, "cannot prime package directory cache: %v\n", err) }

	if err := repGen.writeCovHTMLFiles(ctx, os.Stderr); err != nil { return fatal(8, "cannot write HTML coverage files: %v\n", err) }

	tb := &treeBuilder{
		fsys:    &localFS{},
		modName: repGen.modName,
		outRoot: repGen.outRoot,
		cov:     repGen.cov,
	}

	var treeHTML string
	if treeHTML, err = tb.buildTree(ctx, os.Stderr); err != nil { return fatal(9, "cannot build tree HTML: %v\n", err) }

	if err := repGen.writeIndexHTMLFile(ctx, indexHTMLFile, treeHTML); err != nil { return fatal(10, "cannot write %q: %v\n", indexHTMLFile, err) }

	if err := repGen.writeStaticFiles(); err != nil { return fatal(11, "cannot write static files: %v\n", err) }

	if err := repGen.printCoverage(ctx, os.Stdout); err != nil { return fatal(12, "cannot print per-file coverage figures: %v\n", err) }

	// TODO(jbunds): add a method to run `python3 -m http.server -d repGen.outRoot.Name()`

	if err := repGen.maybeOpenHTML(filepath.Base(indexHTMLFile), noBrowser); err != nil { return fatal(13, "cannot open %q: %v\n", filepath.Base(indexHTMLFile), err) }

	return 0
}

// fatal logs a formatted message to stderr and returns the exit code.
func fatal(code int, format string, args ...any) int {
	fmt.Fprintf(os.Stderr, format + "\n", args...)
	return code
}

func newReportGenerator(goModFile, profilePath string, profiles []*cover.Profile, outDir string) (*reportGenerator, error) {
	repGen := &reportGenerator{
		fsys:          &localFS{},
		modFile:       filepath.Clean(goModFile),
		profilePath:   filepath.Clean(profilePath),
		profiles:      profiles,
		embeddedFiles: embeddedFiles,
		staticFiles:   []string{
			"html/code.html",
			"img/favicon.ico",
			"img/go-blue-gradient.svg",
			"css/style.css",
			"css/tree.css",
			"js/events.js",
			"js/child.js",
		},
		styleCSSFilename: "style.css",
		childJSFilename:  "child.js",
	}

	info, err := repGen.fsys.Stat(outDir)
	if err != nil || !info.IsDir() {
		if err := repGen.fsys.MkdirAll(outDir, 0700); err != nil {
			return nil, fmt.Errorf("cannot create directory %q: %w", outDir, err)
		}
	}

	root, err := os.OpenRoot(outDir)
	if err != nil {
		return nil, fmt.Errorf("cannot open %q: %v", outDir, err)
	}
	repGen.outRoot = root

	return repGen, nil
}

// getModName reads the repo's root go.mod file to determine the name of the Go module.
func (rg *reportGenerator) getModName(ctx context.Context, goModFile string) error {
	if err := ctx.Err(); err != nil { return err }

	goMod, err := rg.fsys.ReadFile(goModFile)
	if err != nil                          { return fmt.Errorf("cannot read %q: %w",  goModFile, err) }
	modFile, err := modfile.Parse(goModFile, goMod, nil)
	if err != nil || modFile.Module == nil { return fmt.Errorf("cannot parse %q: %w", goModFile, err) }
	rg.modName = modFile.Module.Mod.Path

	return nil
}

// getRepoURL converts a remote URL to an HTTP URL for subsequent use in writeIndexHTMLFile.
func (rg *reportGenerator) getRemoteURL(runner runner, goModFile string) error {
	// handles custom import paths (vanity URLs) resolved via Go's HTML <meta> tag discovery mechanism:
	//
	//   <meta name="go-import" content="import-prefix vcs repo-root subdir">
	//
	// see also https://pkg.go.dev/cmd/go#hdr-Fully_qualified_import_paths

	var stdout, stderr bytes.Buffer

	cmd       := exec.Command("git", "config", "--get", "remote.origin.url")
	cmd.Dir    = filepath.Dir(goModFile)
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	if err := runner.Run(cmd); err != nil {
		rg.repoURL = "https://" + rg.modName // fallback to modName
		return nil
	}

	remoteURL := strings.TrimSpace(stdout.String())

	if idx := strings.Index(remoteURL, "@"); idx != -1 {
		remoteURL = remoteURL[idx + 1:]
	}

	remoteURL = strings.TrimPrefix(remoteURL, "ssh://")
	remoteURL = strings.TrimPrefix(remoteURL, "git://")

	if !strings.HasPrefix(remoteURL, "http://" ) &&
	   !strings.HasPrefix(remoteURL, "https://") {
		 remoteURL = "https://" + strings.Replace(remoteURL, ":", "/", 1)
	}

	u, err  := url.Parse(remoteURL)
	if err  != nil { return err }

	httpURL := fmt.Sprintf("https://%s%s", u.Host, u.Path)
	httpURL  = strings.TrimSuffix(httpURL, ".git")
	httpURL  = strings.TrimSuffix(httpURL, "/")

	rg.repoURL = httpURL

	return nil
}

// getAllPkgPaths extracts all unique package paths from the
// coverage profile file for subsequent use in primePkgDirCache.
func (rg *reportGenerator) getAllPkgPaths(ctx context.Context) ([]string, error) {
	if err := ctx.Err(); err != nil { return nil, err }

	f, err := rg.fsys.Open(filepath.Clean(rg.profilePath))
	if err != nil { return nil, err }

	defer func() {
		closeErr := f.Close()
		if err == nil { err = closeErr }
	}()

	pkgSet  := make(map[string]struct{})
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := scanner.Text()
		if strings.HasPrefix(line, "mode:") { continue }

		parts := strings.Split(line, ":")
		if len(parts) < 2 { continue }

		pkgSet[filepath.Dir(parts[0])] = struct{}{}
	}

	allPaths := make([]string, 0, len(pkgSet))
	for p := range pkgSet { allPaths = append(allPaths, p) }

	return allPaths, scanner.Err()
}

// primePkgDirCache primes rg.pkgDirCache for subsequent use in buildCovHTML.
func (rg *reportGenerator) primePkgDirCache(ctx context.Context, pkgLoader pkgLoader) error {
	if err := ctx.Err(); err != nil { return err }

	allPkgPaths, err := rg.getAllPkgPaths(ctx)
	if err != nil { return err }

	cfg := &packages.Config{
		Mode:  packages.NeedFiles | packages.NeedModule | packages.NeedName,
		Tests: false,
		Dir:   filepath.Dir(rg.modFile),
	}
	pkgs, err := pkgLoader(cfg, allPkgPaths...)
	if err != nil { return err }

	cache := make(map[string]string)

	for _, pkg := range pkgs {
		if len(pkg.GoFiles) > 0 {
			cache[pkg.PkgPath] = filepath.Dir(pkg.GoFiles[0])
		}
	}

	rg.pkgDirCache = cache

	return nil
}

// printCoverage prints per-file coverage percentages to stdout.
func (rg *reportGenerator) printCoverage(ctx context.Context, w io.Writer) error {
	if err := ctx.Err(); err != nil { return err }

	keys       := slices.Collect(maps.Keys(rg.cov))
	maxPathLen := len(slices.MaxFunc(keys, func(a, b string) int {
		return cmp.Compare(len(a), len(b))
	}))

	maxPathLen = max(maxPathLen, 5) // 5 == len("Total")

	// TODO(jeff): allow users to chose how the rows rendered in the tree should be sorted;
	//             default should probably path-depth, then alphanumerically, just like here
	slices.SortFunc(keys, func(a, b string) int {
		depthA, depthB := strings.Count(a, "/"), strings.Count(b, "/")
		if depthA != depthB { return cmp.Compare(depthA, depthB) } // sort by path depth
		return cmp.Compare(a, b)                                   // sort alphanumerically
	})

	divider := strings.Repeat("—", maxPathLen + 9) + "\n" // 9 == 2 spaces + len("100.00%")

	ew := newErrorWriter(w)
	ew.write("File")
	ew.write(strings.Repeat(" ", maxPathLen - 4 + 1))
	ew.write("Coverage\n")
	ew.write(divider)

	for _, path := range keys {
		cov     := rg.cov[path]
		percent := 0.0
		if cov.total > 0 {
			percent = float64(cov.covered) / float64(cov.total) * 100
		}
		rg.writeRow(ew, path, percent, maxPathLen)
	}

	totalPercent    := 0.0
	totalCovered    := rg.totalCovered.Load()
	totalStatements := rg.totalStatements.Load()
	if totalStatements > 0 {
		totalPercent = float64(totalCovered) / float64(totalStatements) * 100
	}

	ew.write(divider)
	rg.writeRow(ew, "Total", totalPercent, maxPathLen)

	return ew.err()
}

func (rg *reportGenerator) writeRow(ew *errorWriter, path string, percent float64, maxPathLen int) {
	const (
		green = "\033[32m"
		red   = "\033[31m"
	)
	ew.write(path)
	ew.write(strings.Repeat(" ", maxPathLen-len(path)+2))
	pct       := strconv.FormatFloat(percent, 'f', 2, 64)
	colorCode := green
	if percent < 50 { colorCode = red }
	ew.write(strings.Repeat(" ", 6-len(pct)))
	ew.writeColor(pct+"%", colorCode)
	ew.write("\n")
}

// maybeOpenHTML opens the generated index.html file in the
// default browser when stdout is a TTY and -n is not set.
func (rg *reportGenerator) maybeOpenHTML(indexHTMLFile string, noBrowser bool) error {
	if noBrowser || isTerm(os.Stdout) { return nil }

	absPath, err := filepath.Abs(filepath.Join(rg.outRoot.Name(), indexHTMLFile)) // file:// scheme
	if err != nil {
		return err
	}

	var cmd *exec.Cmd
	switch os := runtime.GOOS; os {
	case "darwin":
		cmd = exec.Command("open",         absPath) // #nosec G204 G702 - no shell (no injection); absPath confined to outRoot (no path escape)
	case "windows":
		cmd = exec.Command("explorer.exe", absPath) // #nosec G204 G702 - no shell (no injection); absPath confined to outRoot (no path escape)
	case "linux":
		cmd = exec.Command("xdg-open",     absPath) // #nosec G204 G702 - no shell (no injection); absPath confined to outRoot (no path escape)
	default:
		return fmt.Errorf("unrecognized OS: %s", os)
	}
	return new(realRunner).Run(cmd)
}

// isTerm determines if the specified writer is connected to a terminal.
func isTerm(v any) bool {
	if testing.Testing()                     ||
	   os.Getenv("GITHUB_ACTIONS") == "true" || // https://docs.github.com/actions/reference/workflows-and-actions/variables
	   os.Getenv("CI"            ) == "true" { return false }
	fd := getFD(v)
	if fd < 0 { return false }
	return term.IsTerminal(fd)
}

// getFD returns the file descriptor of the provided argument.
func getFD(w any) int {
	if f, ok := w.(interface{ Fd() uintptr }); ok { return int(f.Fd()) }
	return -1
}
