// Package main writes HTML files for each Go source file listed in the user-specified Go coverage profile file.
//
// This module also generates a directory tree HTML file rendered within an iframe of the index HTML file.
//
// The header portion of the index HTML file will also render two buttons if the browser's CORS policies allow it. These buttons are:
//
//   "theme"                  - toggles between two hardcoded "light" and "dark" themes
//   "expand" (or "collapse") - toggles the opening (or closing) of all subdirectories rendered within the tree HTML document
//
// Note that the "theme" and "expand" / "collapse" buttons will not be rendered when the index page is loaded via the file:// scheme.
//
// A simple workaround is to instantiate an HTTP server to serve the HTML files, e.g.:
//
//   $ python3 -m http.server 8000
//
// and then load http://localhost:8000/ in a browser.
package main

import (
	"cmp"
	"embed"
	"errors"
	"flag"
	"fmt"
	"html"
	"io"
	"io/fs"
	"maps"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"text/template"

	"golang.org/x/mod/modfile"
	"golang.org/x/mod/module"
	"golang.org/x/tools/cover"
)

//go:embed favicon.ico go-blue-gradient.svg index.html style.css tree.css
var embeddedFiles embed.FS

var (
	indexHTML      = "index.html" // template
	treeHTML       = "tree.html"  // generated by tree.go
	styleCSS       = "style.css"  // template
	ancillaryFiles = []string{
		"favicon.ico",
		"go-blue-gradient.svg",
		"tree.css"}
)

type coverage struct {
	covered int
	total   int
}

// wrappers to make testing easier
type localFS struct {
	fs.FS
}

type writeFS interface {
	fs.FS
	Create(string) (io.WriteCloser, error)
	MkdirAll(string, fs.FileMode) error
	WriteFile(string, []byte, fs.FileMode) error
}

func (lfs *localFS) Create   (name string) (io.WriteCloser,               error) { return os.Create(filepath.Clean(name)) }
func (lfs *localFS) MkdirAll (path string, perm fs.FileMode)              error  { return os.MkdirAll(path, perm) }
func (lfs *localFS) WriteFile(name string, data []byte, perm fs.FileMode) error  { return os.WriteFile(name, data, perm) }

type stringWriter interface {
	io.Writer
	Reset()
	String() string
}

// stores state, simplifies method signatures, avoids copying values, and makes testing easier
type reportGenerator struct {
	fsys            writeFS
	embeddedFiles   fs.FS
	modName         string
	srcRoot         string
	outRoot         string
	profilePath     string
	profiles        []*cover.Profile
	cov             map[string]coverage
	totalCovered    int
	totalStatements int
	maxWidth        int
	ancillaryFiles  []string
}

func main() {
	profilePath, outRoot, err := flags(flag.CommandLine, filterArgs(os.Args[1:]))
	if err != nil {
		fmt.Fprintf(os.Stderr, "cannot parse flags: %v\n", err)
		os.Exit(1)
	}

	profiles, err := cover.ParseProfiles(profilePath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "cannot parse coverage profile file: %v\n", err)
		os.Exit(2)
	}

	repGen := &reportGenerator{
		fsys:           &localFS{os.DirFS(".")},
		embeddedFiles:  embeddedFiles,
		outRoot:        outRoot,
		profilePath:    profilePath,
		profiles:       profiles,
		ancillaryFiles: ancillaryFiles,
	}

	if err := repGen.getModName(); err != nil { // sets repGen.modName
		fmt.Fprintf(os.Stderr, "cannot determine module name: %v\n", err)
		os.Exit(3)
	}

	if err := repGen.getSrcRoot(); err != nil { // sets repGen.srcRoot
		fmt.Fprintf(os.Stderr, "cannot determine source root: %v\n", err)
		os.Exit(4)
	}

	if err := repGen.writeCovHTMLFiles(&strings.Builder{}); err != nil { // sets repGen.cov
		fmt.Fprintf(os.Stderr, "cannot write HTML coverage files: %v\n", err)
		os.Exit(5)
	}

	repGen.printCoverage() // requires repGen.cov

	if err := repGen.writeIndexHTML(indexHTML); err != nil { // requires repGen.modName
		fmt.Fprintf(os.Stderr, "cannot write %q: %v\n", indexHTML, err)
		os.Exit(6)
	}

	if repGen.maxWidth, err = writeTreeHTML(outRoot, treeHTML, repGen.cov); err != nil {
		fmt.Fprintf(os.Stderr, "cannot write %q: %v\n", treeHTML, err)
		os.Exit(7)
	}

	if err := repGen.writeStyleCSS(styleCSS); err != nil { // requires repGen.maxWidth
		fmt.Fprintf(os.Stderr, "cannot write %s: %v\n", styleCSS, err)
		os.Exit(8)
	}

	if err := repGen.writeAncillaryFiles(); err != nil {
		fmt.Fprintf(os.Stderr, "cannot write ancillary files: %v\n", err)
		os.Exit(9)
	}
}

// getModName tries to read the go.mod file to determine the name of the Go module,
// and falls back to inspecting the coverage profiles if that fails
func (rg *reportGenerator) getModName() error {
	goMod, err := fs.ReadFile(rg.fsys, "go.mod")
	if err == nil {
		modFile, err := modfile.Parse("go.mod", goMod, nil)
		if err != nil || modFile.Module == nil { return fmt.Errorf("cannot parse go.mod: %w", err) }
		rg.modName = modFile.Module.Mod.Path
		return nil
	}
	return rg.findCommonRoot() // fallback to inspecting the coverage profiles
}

// findCommonRoot finds the longest path prefix common to all files listed in the Go test coverage profile file.
// downstream code assumes this longest common prefix (sans the trailing "/") specifies the Go module name
func (rg *reportGenerator) findCommonRoot() error {
	if len(rg.profiles) < 1 { return nil }
	common := strings.Split(rg.profiles[0].FileName, "/")
	for _, profile := range rg.profiles[1:] {
		current  := strings.Split(profile.FileName, "/")
		matchLen := 0
		for i := 0; i < min(len(common), len(current)); i++ {
			if common[i] == current[i] {
				matchLen++
			} else {
				break
			}
		}
		common = common[:matchLen]
		if len(common) == 0 { return fmt.Errorf("cannot determine common root") }
	}
	rg.modName = strings.Join(common, "/")
	return nil
}

// getSrcRoot determines the root of the Go source files by the checking for the existence of
// the first source file returned from cover.ParseProfiles in one of the following locations:
//
//   - the current working directory
//   - the parent directory of the coverage profile file (per the value of the -coverprofile flag)
//   - the parent directory of the output path           (per the value of the -path flag)
func (rg *reportGenerator) getSrcRoot() error {
	firstSrcRelPath       := strings.TrimPrefix(rg.profiles[0].FileName, rg.modName + "/")
	profilePathParentDir  := filepath.Dir(rg.profilePath)
	profilePathSrcRelPath := filepath.Join(profilePathParentDir, firstSrcRelPath)
	outRootParentDir      := filepath.Dir(rg.outRoot)
	outRootSrcRelPath     := filepath.Join(outRootParentDir, firstSrcRelPath)
	switch {
	case fileExists(rg.fsys, firstSrcRelPath):
		rg.srcRoot = "."
	case fileExists(rg.fsys, profilePathSrcRelPath):
		rg.srcRoot = profilePathParentDir
	case fileExists(rg.fsys, outRootSrcRelPath):
		rg.srcRoot = outRootParentDir
	default:
		return fmt.Errorf("cannot locate source root")
	}
	return nil
}

// fileExists returns a boolean indicating whether or not a given file exists
func fileExists(fsys fs.FS, path string) bool {
	_, err := fs.Stat(fsys, path)
	return !errors.Is(err, os.ErrNotExist)
}

// writeCovHTMLFiles calculates per-file coverage percentages and writes a
// *.go.html file for each Go source file listed in the coverage profile file
func (rg *reportGenerator) writeCovHTMLFiles(w stringWriter) error {
	rg.cov = make(map[string]coverage, len(rg.profiles))

	for _, profile := range rg.profiles { // calculate per-file coverage
		var fileStatements, fileCovered int
		for _, block := range profile.Blocks {
			fileStatements += int(block.NumStmt)
			if block.Count > 0 {
				fileCovered += int(block.NumStmt)
			}
		}

		rg.totalCovered    += fileCovered
		rg.totalStatements += fileStatements

		localPath := strings.TrimPrefix(profile.FileName, rg.modName + "/")
		rg.cov[localPath] = coverage{
			covered: fileCovered,
			total:   fileStatements,
		}

		w.Reset()
		if err := rg.buildCovHTML(w, profile, localPath); err != nil {
			return fmt.Errorf("cannot write HTML file for %s: %w", localPath, err)
		}

		outPath := filepath.Clean(filepath.Join(rg.outRoot, localPath + ".html"))
		if err := rg.fsys.MkdirAll(filepath.Dir(outPath), 0700); err != nil {
			return fmt.Errorf("cannot create directory: %w", err)
		}
		if err := rg.fsys.WriteFile(outPath, []byte(w.String()), 0600); err != nil {
			return fmt.Errorf("cannot write file %q: %w", outPath, err)
		}
	}
	return nil
}

// buildCovHTML builds the HTML content for a single *.go.html file, with green (covered) and red (uncovered) lines to indicate test coverage
func (rg *reportGenerator) buildCovHTML(w io.Writer, profile *cover.Profile, localPath string) error {
	srcFile  := filepath.Clean(filepath.Join(rg.srcRoot, localPath))
	src, err := fs.ReadFile(rg.fsys, srcFile)
	if err != nil { return fmt.Errorf("cannot read source file %q: %w", srcFile, err) }

	depth      := strings.Count(localPath, "/")
	cssRelPath := styleCSS
	if depth > 0 {
		cssRelPath = strings.Repeat("../", depth) + cssRelPath // ensures both http:// and file:// schemes correctly resolve the path to the CSS file
	}

	if err := writePreamble(w, cssRelPath, localPath); err != nil {
		return fmt.Errorf("cannot write preamble: %w", err)
	}

	pos := 0
	for _, b := range profile.Boundaries(src) {
		if _, err := io.WriteString(w, html.EscapeString(string(src[pos:b.Offset]))); err != nil {
			return fmt.Errorf("cannot write code block HTML: %w", err)
		}
		if b.Start {
			class := "miss"
			if b.Count > 0 {
				class = "hit"
			}
			if _, err := fmt.Fprintf(w, "<span class='%s'>", class); err != nil {
				return fmt.Errorf("cannot write coverage section %q start: %w", class, err)
			}
		} else {
			if _, err := io.WriteString(w, "</span>"); err != nil {
				return fmt.Errorf("cannot write coverage section end: %w", err)
			}
		}
		pos = b.Offset
	}

	if _, err := io.WriteString(w, html.EscapeString(string(src[pos:]))); err != nil {
		return fmt.Errorf("cannot write code block HTML: %w", err)
	}
	if err := writePostamble(w); err != nil {
		return fmt.Errorf("cannot write postamble: %w", err)
	}

	return nil
}

func writePreamble(w io.Writer, cssRelPath, localPath string) error {
	_, err := fmt.Fprintf(w, `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<link rel="stylesheet" href="%s" type="text/css">
<title>%s</title>
</head>
<body id="code">
<pre>`, cssRelPath, localPath)
	return err
}

func writePostamble(w io.Writer) error {
	_, err := io.WriteString(w, `</pre>
<script>
try {
  const parentTheme = window.parent.document.documentElement.getAttribute('theme');
  if (parentTheme) document.documentElement.setAttribute('theme', parentTheme);
} catch (e) {
  console.warn('direct parent access blocked by browser; waiting for postMessage');
}

window.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SET_THEME') document.documentElement.setAttribute('theme', event.data.theme);
});
</script>
</body>
</html>`)
	return err
}

// printCoverage prints per-file coverage percentages to stdout
func (rg *reportGenerator) printCoverage() {
	keys       := slices.Collect(maps.Keys(rg.cov))
	maxPathLen := len(slices.MaxFunc(keys, func(a, b string) int {
		return cmp.Compare(len(a), len(b))
	}))

	maxPathLen = max(maxPathLen, 5) // 5 == len("Total")

	fmtHeader := fmt.Sprintf("%%-%ds %%7s\n",        maxPathLen)
	fmtData   := fmt.Sprintf("%%-%ds  %%6.2f%%%%\n", maxPathLen)

	fmt.Printf(fmtHeader, "File", "Coverage")
	fmt.Println(strings.Repeat("—", maxPathLen + 9)) // 9 == 2 spaces + len("100.00%")

	// TODO(jeff): allow users to chose how the rows rendered in the tree should be sorted;
	//             default should probably path-depth, then alphanumerically, just like here
	slices.SortFunc(keys, func(a, b string) int {
		depthA := strings.Count(a, "/")
		depthB := strings.Count(b, "/")
		if depthA != depthB {
			return cmp.Compare(depthA, depthB) // sort by path depth
		}
		return cmp.Compare(a, b) // sort alphanumerically
	})

	for _, path := range keys {
		cov     := rg.cov[path]
		percent := 0.0
		if cov.total > 0 {
			percent = float64(cov.covered) / float64(cov.total) * 100
		}
		fmt.Printf(fmtData, path, percent)
	}

	totalPercent := 0.0
	if rg.totalStatements > 0 {
		totalPercent = float64(rg.totalCovered) / float64(rg.totalStatements) * 100
	}

	fmt.Println(strings.Repeat("—", maxPathLen + 9)) // 9 == 2 spaces + len("100.00%")
	fmt.Printf(fmtData, "Total", totalPercent)
}

// writeIndexHTML writes the index HTML file, which contains two template parameters
// (ModName and ModURL), and hosts two iframes (directory tree & source code), 
func (rg *reportGenerator) writeIndexHTML(indexHTML string) error {
	repoURL, _, ok := module.SplitPathVersion(rg.modName)
	if !ok { repoURL = rg.modName }
	data := struct{
		ModName, ModURL string
	}{
		ModName: rg.modName,
		ModURL:  "https://" + repoURL,
	}
	return rg.writeTemplateFile(indexHTML, data)
}

// writeStyleCSS writes the style.css file, which contains a single "MaxWidth" template parameter
func (rg *reportGenerator) writeStyleCSS(styleCSS string) error {
	data := struct{
		MaxWidth int
	}{
		MaxWidth: rg.maxWidth,
	}
	return rg.writeTemplateFile(styleCSS, data)
}

func (rg *reportGenerator) writeTemplateFile(file string, tmplVars any) error {
	outFile   := filepath.Clean(filepath.Join(rg.outRoot, file))
	tmpl, err := template.ParseFS(rg.embeddedFiles, file)
	if err != nil { return fmt.Errorf("cannot parse %q: %w", file, err) }
	f, err := rg.fsys.Create(outFile)
	if err != nil { return fmt.Errorf("cannot create %q: %w", outFile, err) }
	if err := tmpl.Execute(f, tmplVars); err != nil { return fmt.Errorf("cannot render template: %w", err) }
	return f.Close()
}

// writeAncillaryFiles writes the supporting files defined per the ancillaryFiles global variable to the user-specified path
func (rg *reportGenerator) writeAncillaryFiles() error {
	for _, file := range rg.ancillaryFiles {
		outFile   := filepath.Clean(filepath.Join(rg.outRoot, file))
		f, err    := rg.fsys.Create(outFile)
		if err != nil { return fmt.Errorf("cannot create %q: %w", outFile, err) }
		data, err := fs.ReadFile(rg.embeddedFiles, file)
		if err != nil { return fmt.Errorf("cannot read %q: %w", file, err) }
		if _, err := fmt.Fprint(f, string(data)); err != nil { return fmt.Errorf("cannot write file %q: %w", outFile, err) }
		if err := f.Close(); err != nil { return fmt.Errorf("cannot close file %q: %w", outFile, err) }
	}
	return nil
}

// filterArgs discards any arguments up to and including "--", potentially useful for testing
func filterArgs(args []string) []string {
	for i, arg := range args {
		if arg == "--" {
			args = args[i+1:]
			break
		}
	}
	return args
}
