// Package main writes HTML files for each Go source file listed in the user-specified Go coverage profile file.
//
// This module also generates a directory tree HTML file rendered within an iframe of the index HTML file.
//
// The header portion of the index HTML file will also render two buttons if the browser's CORS policies allow it. These buttons are:
//
//   "expand" (or "collapse") - toggles opening (or closing) all subdirectories of the source tree
//   "lines"                  - toggles showing or hiding a column of line numbers along the left side of the source code
//   "theme"                  - toggles between "light" and "dark" themes
//
// Note that the "expand" / "collapse", "lines", and "theme" buttons will not be rendered when the index page is loaded via the file:// scheme.
package main

import (
	"bufio"
	"bytes"
	"context"
	"embed"
	"errors"
	"flag"
	"fmt"
	"io"
	"io/fs"
	"net/url"
	"os"
	"os/exec"
	"os/signal"
	"path/filepath"
	"strings"
	"sync/atomic"
	"syscall"

	"golang.org/x/mod/modfile"
	"golang.org/x/tools/cover"
	"golang.org/x/tools/go/packages"
)

//go:embed html/* img/* css/* js/*
var embeddedFiles embed.FS

// coverage tracks per-file coverage.
type coverage struct {
	covered uint64
	total   uint64
}

// coverageState accumulates coverage data.
type coverageState struct {
	cov             map[string]coverage // per-file coverage data
	totalCovered    atomic.Uint64       // module-wide total number of statements covered
	totalStatements atomic.Uint64       // module-wide total number of statements
	sort            func() []string     // returns file paths in the order they are printed to stdout
}

// reportGenerator orchestrates the generation of the HTML report.
type reportGenerator struct {
	fsys             writeFS           // wrapper around the os functions used herein
	embeddedFiles    fs.FS             // templates and static files referenced by the generated HTML
	modFile          string            // path to go.mod
	modName          string            // module name
	repoURL          string            // repository URL written to the repo link in index.html template via .ModURL
	outRoot          rootHandle        // output root for the generated HTML files, per -outdir
	profilePath      string            // value of the -coverprofile flag
	profiles         []*cover.Profile  // coverage profiles generated by `go tool cover`
	covState         *coverageState    // covState accumulates coverage data during report generation
	pkgDirCache      map[string]string // pkgDirCache maps canonical Go packages to their respective paths on disk
	staticFiles      []string          // static CSS, HTML, and image files required by the generated HTML
	iconFilename     string            // name of the icon file included by index.html and generated source HTML files
	styleCSSFilename string            // name of the CSS file included by index.html and generated source HTML files
	childJSFilename  string            // name of the JS file included by generated source HTML files that handles toggling the theme and line numbers
	write            bool              // true when static and generated files should be written to disk
}

func main() {
	os.Exit(run())
}

func run() int {
	ctx, stop := signal.NotifyContext(context.Background(),
		syscall.SIGINT,  // ctrl+c
		syscall.SIGTERM, // standard kill signal
		syscall.SIGHUP,  // terminal closed, SSH disconnection, etc
	)
	defer stop()

	signal.Notify(make(chan os.Signal, 1), syscall.SIGPIPE) // prevent SIGPIPE from killing the process; writes return EPIPE (handled below)

	fv, err := flags(flag.CommandLine, filterArgs(os.Args[1:]))
	if err != nil { return fatal(1, "cannot parse flags: %v", err) }

	rg, err := newReportGenerator(fv)
	if err != nil { return fatal(2, "cannot instantiate report generator: %v", err) }
	defer rg.outRoot.Close()

	var progressWriter io.Writer = os.Stderr
	if !isTerm(os.Stderr) { progressWriter = io.Discard }

	if err := rg.getModName(fv);                         err != nil { return fatal(3, "cannot determine module name: %v",         err) }
	if err := rg.getRemoteURL(&realRunner{}, fv);        err != nil { return fatal(4, "cannot determine remote URL: %v",          err) }
	if err := rg.primePkgDirCache(packages.Load);        err != nil { return fatal(5, "cannot prime package directory cache: %v", err) }

	fmt.Fprintf(os.Stderr, "processing %d source files...", len(rg.profiles))
	if !isTerm(os.Stdin) { fmt.Fprintln(os.Stderr) }

	if err := rg.writeCovHTMLFiles(ctx, progressWriter); err != nil { return fatal(6, "cannot write HTML coverage files: %v",     err) }

	tb := &treeBuilder{
		fsys:     &localFS{},
		modName:  rg.modName,
		outRoot:  rg.outRoot,
		covState: rg.covState,
	}

	if rg.write {
		var treeHTML string
		if treeHTML, err = tb.buildTree(ctx, progressWriter); err != nil { return fatal(7, "cannot build tree HTML: %v",    err) }
		if err := rg.writeIndexHTMLFile(treeHTML);            err != nil { return fatal(8, "cannot write index.html: %v",   err) }
		if err := rg.writeStaticFiles();                      err != nil { return fatal(9, "cannot write static files: %v", err) }
	}

	if err := rg.covState.printCoverage(os.Stdout); err != nil {
		if !errors.Is(err, syscall.EPIPE) { // syscall.EPIPE indicates the downstream pipe closed; not an error
			return fatal(10, "cannot print coverage: %v", err)
		}
	}

	if err := rg.maybeOpenBrowser(fv); err != nil { return fatal(11, "cannot open browser: %v", err) }

	return 0
}

// fatal logs a formatted message to stderr and returns the exit code.
func fatal(code int, format string, args ...any) int {
	fmt.Fprintf(os.Stderr, format + "\n", args...)
	return code
}

func newReportGenerator(fv *flagVals) (*reportGenerator, error) {
	profiles, err := cover.ParseProfiles(fv.coverProfileFile) // TODO(jbunds): (maybe?) add an adapter to handle both legacy textfmt and binary coverage profiles
	if err != nil {
		return nil, fmt.Errorf("cannot parse coverage profile file: %w", err)
	}

	rg := &reportGenerator{
		fsys:             &localFS{},
		covState:         &coverageState{},
		outRoot:          nullRoot{},
		modFile:          filepath.Clean(fv.goModFile),
		profilePath:      filepath.Clean(fv.coverProfileFile),
		profiles:         profiles,
		embeddedFiles:    embeddedFiles,
		iconFilename:     "favicon.ico",
		childJSFilename:  "child.js",
		styleCSSFilename: "style.css",
		staticFiles:      []string{
			"html/code.html",
			"img/favicon.ico",
			"img/go-blue-gradient.svg",
			"css/style.css",
			"css/tree.css",
			"js/events.js",
			"js/child.js",
		},
	}

	rg.covState.sort = fv.sortOrder.bind(rg.covState)
	rg.write         = fv.outDir != "/dev/null" && fv.outDir != "nul"

	if rg.write {
		info, err := rg.fsys.Stat(fv.outDir)
		if err != nil || !info.IsDir() {
			if err := rg.fsys.MkdirAll(fv.outDir, 0700); err != nil {
				return nil, fmt.Errorf("cannot create directory %q: %w", fv.outDir, err)
			}
		}

		root, err := os.OpenRoot(fv.outDir)
		if err != nil {
			return nil, fmt.Errorf("cannot open %q: %v", fv.outDir, err)
		}
		rg.outRoot = root
	}

	return rg, nil
}

// getModName reads the specified go.mod file to determine the name of the Go module.
func (rg *reportGenerator) getModName(fv *flagVals) error {
	goMod, err   := rg.fsys.ReadFile(fv.goModFile)
	if err != nil                          { return fmt.Errorf("cannot read %q: %w",  fv.goModFile, err) }
	modFile, err := modfile.Parse(fv.goModFile, goMod, nil)
	if err != nil || modFile.Module == nil { return fmt.Errorf("cannot parse %q: %w", fv.goModFile, err) }
	rg.modName = modFile.Module.Mod.Path

	return nil
}

// getRepoURL converts a remote URL to an HTTP URL for subsequent use in writeIndexHTMLFile.
func (rg *reportGenerator) getRemoteURL(runner runner, fv *flagVals) error {
	// handles custom import paths (vanity URLs) resolved via Go's HTML <meta> tag discovery mechanism:
	//
	//   <meta name="go-import" content="import-prefix vcs repo-root subdir">
	//
	// see also https://pkg.go.dev/cmd/go#hdr-Fully_qualified_import_paths

	var stdout, stderr bytes.Buffer

	cmd       := exec.Command("git", "config", "--get", "remote.origin.url")
	cmd.Dir    = filepath.Dir(fv.goModFile)
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	if err := runner.Run(cmd); err != nil {
		rg.repoURL = "https://" + rg.modName // fallback to modName
		return nil
	}

	remoteURL := strings.TrimSpace(stdout.String())

	if idx := strings.Index(remoteURL, "@"); idx != -1 {
		remoteURL = remoteURL[idx + 1:]
	}

	remoteURL = strings.TrimPrefix(remoteURL, "ssh://")
	remoteURL = strings.TrimPrefix(remoteURL, "git://")

	if !strings.HasPrefix(remoteURL, "http://" ) &&
	   !strings.HasPrefix(remoteURL, "https://") {
		 remoteURL = "https://" + strings.Replace(remoteURL, ":", "/", 1)
	}

	u, err  := url.Parse(remoteURL)
	if err  != nil { return err }

	httpURL := fmt.Sprintf("https://%s%s", u.Host, u.Path)
	httpURL  = strings.TrimSuffix(httpURL, ".git")
	httpURL  = strings.TrimSuffix(httpURL, "/")

	rg.repoURL = httpURL

	return nil
}

// getAllPkgPaths extracts all unique package paths from the
// coverage profile file for subsequent use in primePkgDirCache.
func (rg *reportGenerator) getAllPkgPaths() ([]string, error) {
	f, err := rg.fsys.Open(filepath.Clean(rg.profilePath))
	if err != nil { return nil, err }

	defer func() {
		closeErr := f.Close()
		if err == nil { err = closeErr }
	}()

	pkgSet  := make(map[string]struct{})
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := scanner.Text()
		if strings.HasPrefix(line, "mode:") { continue }

		parts := strings.Split(line, ":")
		if len(parts) < 2 { continue }

		pkgSet[filepath.Dir(parts[0])] = struct{}{}
	}

	allPaths := make([]string, 0, len(pkgSet))
	for p := range pkgSet { allPaths = append(allPaths, p) }

	return allPaths, scanner.Err()
}

// primePkgDirCache primes rg.pkgDirCache for subsequent use in buildCovHTML.
func (rg *reportGenerator) primePkgDirCache(pkgLoader pkgLoader) error {
	allPkgPaths, err := rg.getAllPkgPaths()
	if err != nil { return err }

	cfg := &packages.Config{
		Mode:  packages.NeedFiles | packages.NeedModule | packages.NeedName,
		Tests: false,
		Dir:   filepath.Dir(rg.modFile),
	}
	pkgs, err := pkgLoader(cfg, allPkgPaths...)
	if err != nil { return err }

	cache := make(map[string]string)

	for _, pkg := range pkgs {
		if len(pkg.GoFiles) > 0 {
			cache[pkg.PkgPath] = filepath.Dir(pkg.GoFiles[0])
		}
	}

	rg.pkgDirCache = cache

	return nil
}
