# https://docs.github.com/actions/reference/workflows-and-actions/metadata-syntax

# reusable composite action which uses these standard actions
# to upload a Go test coverage HTML report to GitHub Pages:
#
#   actions/configure-pages@v6 and
#   actions/upload-pages-artifact@v4 

name:        upload Go test coverage HTML report to GitHub Pages
description: uploads a Go test coverage HTML report to GitHub Pages
author:      jbunds

inputs:
  coverage-report-path:
    description: 'path to the root of the Go coverage report'
    required:    false
    default:     'coverage_report'

runs:
  using: composite
  steps:
    - name: configure GitHub Pages
      id:   configure_pages
      uses: actions/configure-pages@v6

    - name: upload GitHub Pages artifact
      id:   upload_pages_artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: ${{ inputs.coverage-report-path }}
