name: deploy jbunds/coverage coverage report to Pages
on:
  workflow_dispatch: # allows this workflow to be manually triggered from the UI
  release:
    types: [published]
  push:
    branches: [main]
    paths:
      - '**/*.go'
      - '**/go.mod'
concurrency:
  group:              coverage-notes
  cancel-in-progress: false
jobs:
  pages:
    uses: ./.github/workflows/pages.yml
    with:
      go-mod:          go.mod,fractal/go.mod,progress/go.mod
      cover-pkg:       .,fractal/...,progress/...
      test-pkgs: |-
        .
        ./fractal/...
        ./progress/...
      workspace-repos: |-
        jbunds/fractal
        jbunds/progress
