name: deploy jbunds/coverage coverage report to Pages
on:
  workflow_dispatch: # allows this workflow to be manually triggered from the UI
  push:
    branches: [main]
    paths:
      - '**/*.go'
      - '**/go.mod'
      - 'go.work'
jobs:
  pages:
    uses: ./.github/workflows/pages.yml
    with:
      go-mod:          go.work
      cover-pkg:       .,./fractal/...,./progress/...
      test-pkgs: |-
        ./...
        ./fractal/...
        ./progress/...
      workspace-repos: |-
        jbunds/fractal
        jbunds/progress
