name: lint JavaScript

on:
  workflow_dispatch: # allows this workflow to be manually triggered from the UI
  push:
    branches:
      - main
    paths:
      - 'demo/**/*.js'

jobs:
  eslint:
    runs-on: macos-latest

    steps:
    - name: checkout
      uses: actions/checkout@v6

    - name: setup node.js
      uses: actions/setup-node@v6
      with:
        node-version:          'lts/*'
        cache:                 npm
        cache-dependency-path: demo/package-lock.json

    - name:              npm ci
      run:               npm ci
      working-directory: demo

    - name:              eslint
      run:               npx eslint --format json --stats | jq -r '.[].filePath'  # hack to get eslint to list the files it lints
      working-directory: demo
