name: CSS stylelint

on:
  push:
    branches: [ 'main' ]
    paths:
      - '**/*.css'
  pull_request:
    branches: [ 'main' ]
    paths:
      - '**/*.css'
  workflow_dispatch: # allows this workflow to be manually triggered from the UI

permissions: # https://docs.github.com/actions/reference/workflows-and-actions/workflow-syntax#permissions
  contents: read

jobs:
  stylelint:
    name:    stylelint
    runs-on: macos-latest # https://docs.github.com/actions/reference/runners/github-hosted-runners#standard-github-hosted-runners-for--private-repositories
    env:
      NPM_CONFIG_LOGLEVEL: verbose
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-node
      - run:  npm ci
      - run:  npx stylelint '**/*.css' --formatter verbose
