name: CSS Lint (Biome)

on:
  push:
    branches: [ 'main' ]
    paths:
      - '**/*.css'
  pull_request:
    branches: [ 'main' ]
    paths:
      - '**/*.css'
  workflow_dispatch: # allows this workflow to be manually triggered from the UI

permissions: # https://docs.github.com/actions/reference/workflows-and-actions/workflow-syntax#permissions
  contents: read

jobs:
  biome:
    runs-on: ubuntu-latest # https://docs.github.com/actions/reference/runners/github-hosted-runners#standard-github-hosted-runners-for--private-repositories
    steps:
      - uses: actions/checkout@v7
      - uses: biomejs/setup-biome@v2
      - run:  biome ci '**/*.css'
