name: eslint

on:
  workflow_dispatch: # allows this workflow to be manually triggered from the UI
  push:
    branches:
      - main
    paths:
      - 'demo/**/*.js'

jobs:
  lint:
    runs-on: macos-latest

    steps:
    - name: checkout
      uses: actions/checkout@v6

    - name: setup node.js
      uses: actions/setup-node@v6
      with:
        node-version: '25'  # 'lts/*' ?

    - run: npm ci

    - name: eslint
      run: |
        cd demo
        npx eslint .
