name: JS Lint (Biome)

on:
  workflow_dispatch: # allows this workflow to be manually triggered from the UI
  push:
    branches:
      - main
    paths:
      - '**/*.js'

jobs:
  biome:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - name: Setup Biome CLI
      uses: biomejs/setup-biome@v2

    - name: Run Biome
      run:  biome ci validate.js demo/
