# all-in-one reusable workflow which does the following:
#
#   1. generates a Go test coverage HTML report via ./action.yml
#
#   2. uses .github/actions/upload-pages/action.yml to upload
#      the Go test coverage HTML report files to GitHub Pages
#      per these standard actions:
#
#        - actions/configure-pages@v6
#        - actions/upload-pages-artifact@v4
#
#   3. deploys the Go test coverage HTML report to GitHub Pages
#      via actions/deploy-pages@v5

name: deploy coverage report to Pages

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      go-version:
        type:        string
        description: 'Go version'
        required:    false
        default:     '1.26.1'
      go-mod:
        type:        string
        description: 'path to the root go.mod file'
        required:    false
        default:     'go.mod'
      coverage-threshold:
        type:        string
        description: 'coverage threshold percentage'
        required:    false
        default:     '0'
      coverage-report-path:
        type:        string
        description: 'path to the root of the Go coverage report'
        required:    false
        default:     'coverage_report'
  push:
    branches: ['main']
    paths:
      - '**/*.go'

concurrency:          # avoid races
  group:              'pages'
  cancel-in-progress: false

jobs:
  generate-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Go coverage report
        uses: ./  # './' refers to the action.yml file in the root of this repo; external callers should use "jbunds/coverage@v1"
        with:
          go-version:           ${{ inputs.go-version           || '1.26.1'          }}
          go-mod:               ${{ inputs.go-mod               || 'go.mod'          }}
          coverage-threshold:   ${{ inputs.coverage-threshold   || '0'               }}
          coverage-report-path: ${{ inputs.coverage-report-path || 'coverage_report' }}

      - name: upload to GitHub Pages          # https://jbunds.github.io/coverage/
        uses: ./.github/actions/upload-pages  # external callers should use "jbunds/coverage/.github/actions/upload-pages@v1"
        with:
          coverage-report-path: ${{ inputs.coverage-report-path || 'coverage_report' }}

  deploy:
    runs-on: ubuntu-latest
    needs:   generate-and-upload
    permissions: # required permissions for the GITHUB_TOKEN to deploy to GitHub Pages
      contents: read
      pages:    write
      id-token: write
    environment:
      name: github-pages
      url:  ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: deploy to GitHub Pages
        id:   deployment
        uses: actions/deploy-pages@v5
