name: stylelint

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.css'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.css'
  workflow_dispatch: # allows this workflow to be manually triggered from the UI

permissions: # https://docs.github.com/actions/reference/workflows-and-actions/workflow-syntax#permissions
  contents: read

jobs:
  stylelint:              # TODO: consolidate all linters (golangci-lint and stylelint) into a single GitHub Actions workflow called linters.yml
    name:    stylelint
    runs-on: macos-latest # https://docs.github.com/actions/reference/runners/github-hosted-runners#standard-github-hosted-runners-for--private-repositories
    env:
      NPM_CONFIG_LOGLEVEL: verbose
    steps:
      - name: stylelint             # https://stylelint.io/user-guide/get-started/
      - uses: actions/checkout@v6   # https://github.com/actions/checkout
      - uses: actions/setup-node@v6 # https://github.com/actions/setup-node
        with:
          node-version: 25
      - run: npm install stylelint
      - run: npm add -D stylelint stylelint-config-standard # https://stylelint.io/user-guide/get-started/#manual-setup
      - run: npx stylelint '*.css'                          # https://stylelint.io/user-guide/get-started/#manual-setup
