name: validate action

on:
  workflow_dispatch: # allows this workflow to be manually triggered from the UI
  push:
    branches:
      - main
    paths:
      - 'action.yml'

jobs:
  validate:
    runs-on: macos-latest

    steps:
    - name: checkout
      uses: actions/checkout@v6

    - name: setup node.js
      uses: actions/setup-node@v6
      with:
        node-version:          '25'
        cache:                 npm
        cache-dependency-path: '.github/workflows/*.yml'  # obviates need for package-lock.json files according to https://til.simonwillison.net/github-actions/npm-cache-with-npx-no-package

    - name: validate action.yml
      run:  npx action-validator action.yml
