name: validate action

on:
  workflow_dispatch: # allows this workflow to be manually triggered from the UI
  push:
    branches:
      - main
    paths:
      - action.yml

jobs:
  validate:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v6

    - uses: ./.github/actions/setup-node
      with:
        cache-dependency-path: package-lock.json

    - run:  npx @action-validator/cli action.yml
