name: validate action

on:
  workflow_dispatch: # allows this workflow to be manually triggered from the UI
  push:
    branches:
      - main
    paths:
      - 'action.yml'

jobs:
  validate:
    runs-on: macos-latest

    steps:
    - name: checkout
      uses: actions/checkout@v6

    - name: setup node.js
      uses: actions/setup-node@v6
      with:
        node-version: '25'

    - name: validate action.yml
      uses: mpalmer/action-validator@v0.8.0
      run:  npx action-validator action.yml

